---
- name: Deploy AK Weather Bot to New Server
  hosts: app_servers
  become: yes
  gather_facts: no

  pre_tasks:
    - name: 等待服务器 SSH 启动完毕
      wait_for_connection:
        delay: 10
        timeout: 300

    - name: 收集系统信息
      setup:

  tasks:
    - name: 更新 apt 缓存
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: 安装 Docker 和 Docker Compose
      apt:
        name:
          - docker.io
          - docker-compose
        state: present

    - name: 将 ubuntu 用户加入 docker 组
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: 在服务器创建项目文件夹
      file:
        path: /home/ubuntu/AK-Weather-Bot
        state: directory
        owner: ubuntu
        group: ubuntu

    - name: 将代码复制到新服务器
      copy:
        src: "{{ playbook_dir }}/{{ item }}"
        dest: /home/ubuntu/AK-Weather-Bot/
        owner: ubuntu
        group: ubuntu
      with_items:
        - bot.py
        - Dockerfile
        - docker-compose.yml
        - init.sql
        - requirements.txt

    - name: 使用 Docker Compose 启动应用
      environment:
        TELEGRAM_TOKEN: "{{ lookup('env', 'TELEGRAM_TOKEN') }}"
        WEATHER_API_KEY: "{{ lookup('env', 'WEATHER_API_KEY') }}"
      shell: |
        docker-compose down || true
        docker-compose up --build -d
      args:
        chdir: /home/ubuntu/AK-Weather-Bot
